# Generated by Django 4.2.13 on 2024-06-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buyerdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyerUsername', models.CharField(max_length=100)),
                ('buyerPhonenum', models.CharField(max_length=15)),
                ('buyerPassword', models.CharField(max_length=255)),
                ('buyerAddress', models.CharField(max_length=100)),
            ],
        ),
    ]
