# Generated by Django 4.2.13 on 2024-06-23 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('unitPrice', models.IntegerField(max_length=100)),
                ('buyerdb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.buyerdb')),
            ],
        ),
    ]
