# Generated by Django 4.2.13 on 2024-07-07 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('customers', '0003_alter_order_unitprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerdb',
            name='user_profile',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
            preserve_default=False,
        ),
    ]
