# Generated by Django 4.2.13 on 2024-07-01 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbfarmerUsername', models.CharField(max_length=100)),
                ('dbfarmerPhonenum', models.CharField(max_length=15)),
                ('dbfarmerPassword', models.CharField(max_length=255)),
                ('dbfarmerEmail', models.CharField(max_length=100)),
                ('dbfarmerAddress', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'farmer',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('unitPrice', models.IntegerField()),
                ('status', models.BooleanField()),
                ('orderDate', models.DateField()),
                ('completeOrderDate', models.DateField()),
                ('farmer_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.farmerdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amountPaid', models.IntegerField()),
                ('transactionDate', models.DateField()),
                ('status', models.BooleanField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.order')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantityOfEggs', models.IntegerField()),
                ('unitPrice', models.IntegerField()),
                ('numberOfHens', models.IntegerField()),
                ('farmer_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.farmerdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmlocation', models.CharField(max_length=255)),
                ('numberOfHens', models.IntegerField()),
                ('productionRate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('profitLoss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productivity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('farmer_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.farmerdetail')),
            ],
            options={
                'db_table': 'farm',
            },
        ),
    ]
