# Generated by Django 4.2.13 on 2024-06-23 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='farmer_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbfarmerUsername', models.CharField(max_length=100)),
                ('dbfarmerPhonenum', models.CharField(max_length=15)),
                ('dbfarmerPassword', models.CharField(max_length=255)),
                ('dbfarmerEmail', models.CharField(max_length=100)),
                ('dbfarmerAddress', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('unitPrice', models.IntegerField(max_length=100)),
                ('farmer_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.farmer_detail')),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammountPaid', models.IntegerField(max_length=100)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.order')),
            ],
        ),
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantityOfEggs', models.IntegerField(max_length=100)),
                ('unitPrice', models.IntegerField(max_length=100)),
                ('numberOfHens', models.IntegerField(max_length=100)),
                ('farmer_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.farmer_detail')),
            ],
        ),
        migrations.CreateModel(
            name='farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmlocation', models.CharField(max_length=255)),
                ('farmer_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.farmer_detail')),
            ],
        ),
    ]
