# Generated by Django 4.2.13 on 2024-07-07 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0004_rename_user_profile_farmerdetail_user_profile_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmerdetail',
            old_name='user_profile_id',
            new_name='user_profile',
        ),
    ]
